stages:
- name: compile
  steps:
  - runScriptConfig:
      image: golang:1.16
      shellScript: |-
        ls
        pwd
        CGO_ENABLED=0 go build ./cmd/auther
  - runScriptConfig:
      image: golang:1.16
      shellScript: CGO_ENABLED=0 go build ./cmd/cacher
  - runScriptConfig:
      image: golang:1.16
      shellScript: CGO_ENABLED=0 go build ./cmd/ui
- name: image
  steps:
  - publishImageConfig:
      dockerfilePath: ./cacher.Dockerfile
      buildContext: .
      tag: library/xmh-cacher:v1
      pushRemote: true
      registry: core.harbor.domain
    env:
      PLUGIN_INSECURE: "true"
  - publishImageConfig:
      dockerfilePath: ./auther.Dockerfile
      buildContext: .
      tag: library/xmh-auther:v1
      pushRemote: true
      registry: core.harbor.domain
    env:
      PLUGIN_INSECURE: "true"
  - publishImageConfig:
      dockerfilePath: ./ui.Dockerfile
      buildContext: .
      tag: library/xmh-ui:v1
      pushRemote: true
      registry: core.harbor.domain
    env:
      PLUGIN_INSECURE: "true"
timeout: 60
notification: {}
