apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-auther
spec:
  ports:
    - name: default
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    k8s-app: {{ .Release.Name }}-auther
  sessionAffinity: None
  type: ClusterIP
