apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: xmh-go-ui
    app: xmh-go-ui
    version: "1.0"
  name: xmh-go-ui
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: xmh-go-ui
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: xmh-go-ui
        app: xmh-go-ui
        version: "1.0"
    spec:
      containers:
        - imagePullPolicy: IfNotPresent
          name: xmh-go-ui
          resources: { }
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: { }
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
            - mountPath: /config.yaml
              name: config
              subPath: config.yaml
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: my-harbor
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 256
            name: xmh-go-ui-config
            optional: false
          name: config
